kind: PersistentVolume
apiVersion: v1
metadata:
  name: hedwig-eastern-block-rock
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"